export type ValidSkills =
  | "Next.js"
  | "React"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Tailwind CSS"
  | "Java"
  | "Python"
  | "Docker"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Firebase"
  | "Figma"
  | "Supabase"
  | "Vercel"
  | "Flutter"
  | "Dart"
  | "Resend API"
  | "UI/UX"
  | "C#"
  | "Automation"
  | "MSTest"
  | "Agile Methodologies"
  | "Scrum Workflow"
  | "Working in Large Team"
  | "CI/CD Pipelines"
  | "Jira"
  | "SVN"
  | "Jenkins"
  | "Django"
  | "C"
  | "C++"
  | "SSE"
  | "AVX"
  | "Multithreading"
  | "WinAPI"
  | "ATL"
  | "COM"
  | "ROS2"
  | "Nav2"
  | "SLAM"
  | "PX4"
  | "MAVLink"
  | "QGroundControl"
  | "Gazebo"
  | "GitHub"
  | "Docker"
  | "Linux"
  | "Technical Leadership"
  | "Software Architecture"
  | "System Design"
  | "Project Management"
  | "Stakeholder Communication"
  | "Team Mentorship"
  | "Requirements Analysis"
  | "Technical Documentation"
  | "Code Review"
  | "Embedded Systems"
  | "Firmware Development"
  | "Real-Time Systems"
  | "Low-Level Programming"
  | "Makefile"
  | "Algorithms"
  | "Data Structures"
  | "Unit Testing"
  | "NumPy"
  | "Pandas"
  | "Scikit-learn"
  | "BJT"
  | "Analog Electronics"
  | "Circuit Design"
  | "Power Supply Design"
  | "Voltage Regulation"
  | "Backboard API"
  | "ElevenLabs API"
  | "RAG"
  | "Vite"
  | "SQLite"

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "SIMD"
  | "Optimization"
  | "WinAPI"
  | "Multithreading"
  | "GUI Development"
  | "Algorithms"
  | "Data Structures"
  | "Systems Programming"
  | "C Library"
  | "Machine Learning"
  | "Python"
  | "Data Analysis"
  | "Electronics"
  | "Circuit Design"
  | "Analog Systems"
  | "Power Systems"
  | "AI Systems"
  | "RAG"
  | "Full-Stack Development"

export type ValidExpType = "Personal" | "Team"

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "resume"
