export const siteConfig = {
  name: "Clarke Needles",
  authorName: "Clarke Needles",
  username: "ClarkeNeedles",
  description: "Computer Engineer focused on firmware, embedded systems, and robotics, with a passion for building reliable, low-level systems.",
  url: "https://clarkeneedles.com",
  links: {
    linkedin: "https://www.linkedin.com/in/clarke-needles/",
    github: "https://github.com/ClarkeNeedles",
  },
  ogImage:
    "/public/og.png",
  iconIco:
    "/app/favicon.ico",
  logoIcon:
    "/public/logo.png",
  keywords: [
    "Clarke Needles",
    "Computer Engineering",
    "Software Engineer",
    "Embedded Systems Engineer",
    "Firmware Developer",
    "Low-Level Programming",
    "C Programming",
    "C++ Developer",
    "Systems Programming",
    "Real-Time Systems",
    "RTOS",
    "Microcontrollers",
    "Hardware Software Integration",
    "PCB Design",
    "Robotics",
    "Autonomous Systems",
    "UAV Software",
    "ROS2",
    "PX4",
    "SLAM",
    "Computer Vision",
    "Control Systems",
    "Navigation Systems",
    "WinAPI",
    "Windows Development",
    "COM",
    "ATL",
    "Desktop Application Development",
    "Full Stack Developer",
    "AI Systems",
    "RAG Pipeline",
    "Machine Learning",
    "Data Analysis",
    "Next.js",
    "React",
    "TypeScript",
    "Python",
    "Embedded Software",
    "Firmware Engineering",
    "Software Architecture",
    "Engineering Portfolio",
  ]
}
