export const siteConfig = {
  name: "Clarke Needles",
  authorName: "Clarke Needles",
  username: "ClarkeNeedles",
  description: "Clarke Needles is a computer engineer with a passion for firmware, embedded systems, and robotics. With a focus on building reliable, low-level systems, Clarke has experience in C programming, real-time operating systems (RTOS), microcontroller development, and hardware-software integration. Explore Clarke's portfolio to see projects in robotics, autonomous systems, UAV software, computer vision, and more.",
  url: "https://clarkeneedles.com",
  links: {
    linkedin: "https://www.linkedin.com/in/clarke-needles/",
    github: "https://github.com/ClarkeNeedles",
  },
  ogImage:
    "/public/og.png",
  iconIco:
    "/app/favicon.ico",
  logoIcon:
    "/public/logo.png",
  keywords: [
    "Clarke Needles",
    "Computer Engineering",
    "Software Engineer",
    "Embedded Systems Engineer",
    "Firmware Developer",
    "Low-Level Programming",
    "C Programming",
    "C++ Developer",
    "Systems Programming",
    "Real-Time Systems",
    "RTOS",
    "Microcontrollers",
    "Hardware Software Integration",
    "PCB Design",
    "Robotics",
    "Autonomous Systems",
    "UAV Software",
    "ROS2",
    "PX4",
    "SLAM",
    "Computer Vision",
    "Control Systems",
    "Navigation Systems",
    "WinAPI",
    "Windows Development",
    "COM",
    "ATL",
    "Desktop Application Development",
    "Full Stack Developer",
    "AI Systems",
    "RAG Pipeline",
    "Machine Learning",
    "Data Analysis",
    "Next.js",
    "React",
    "TypeScript",
    "Python",
    "Embedded Software",
    "Firmware Engineering",
    "Software Architecture",
    "Engineering Portfolio",
  ]
}
